### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by maxsombra** [samyak-268/gender-classification#4]
i looking the project but i don't know how obtain the features.

is't just a histogram of LBP?

**Comment by samyak-268** [comment]
Hi!
Yes, it is essentially a spatially enhanced uniform-pattern histogram of LBP features. Each input image is divided into 9 equal-sized blocks. The LBP histograms of each sub-image are concatenated to a single global spatially-enhanced histogram which is the feature vector used for classification. I have updated the repo with the code and the project report!

Cheers!
